default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: g1012075
  host: localhost
  database: protospace-41114_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: g1012075
  host: localhost
  database: protospace-41114_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>