
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: protospace_41114_development
  username: dev_user
  password: dev_password

test:
  <<: *default
  database: protospace_41114_test
  username: test_user
  password: test_password

production:
  <<: *default
  adapter: postgresql
  database: protospace_41114_production
  username: protospace_41114
  password: <%= ENV["PROTOSPACE_41114_DATABASE_PASSWORD"] %>
